### ISSUE TITLE
Update dependency Tags in SOPM

### ISSUE THREAD

**Issue by hanneshal** [znuny/ITSMIncidentProblemManagement#1]
Reported by SectorNord.

The dependency information need to be updated. This is related to all ITSM packages

Sample:
https://github.com/znuny/ITSMIncidentProblemManagement/blob/dev/ITSMIncidentProblemManagement.sopm#L242

**Comment by jepf** [comment]
@hanneshal 

Should we just get rid of the exact package version number? Or even the entire intro text?

**Comment by dennykorsukewitz** [comment]
I have created for an internal issue for @NiklasSchmitt 
We are just updating this now.

Internal Issue: 399
